import type { Doula } from "./types";

export const mockDoulas: Doula[] = [
  {
    id: "d-001",
    name: "Alexandra Voight",
    photoUrl: "/assets/doulas/alexandra-voight-upload.png",
    city: "Seattle",
    state: "WA",
    pronouns: "she/her",
    zipCode: "98102",
    specialties: ["postpartum", "birth"],
    tags: ["Postpartum Doula", "Trauma-informed", "Birth Doula", "LGBTQ+ clients", "First time parents"],
    rating: 4.9,
    reviewCount: 12,
    testimonialCount: 12,
    bio: "Supporting families through birth and postpartum with a trauma-informed, LGBTQ+ affirming approach.",
    packagePrice: 1000,
    addonRate: 35,
    slidingScale: true,
    paymentPlans: true,
  },
  {
    id: "d-002",
    name: "Jordan Lee",
    photoUrl: "/assets/doulas/jordan-lee-upload.png",
    city: "Seattle",
    state: "WA",
    pronouns: "she/they",
    zipCode: "98101",
    specialties: ["postpartum", "birth"],
    tags: ["Postpartum Doula", "Trauma-informed", "Birth Doula", "LGBTQ+ clients", "First time parents"],
    rating: 4.8,
    reviewCount: 15,
    testimonialCount: 15,
    bio: "Experienced doula offering compassionate birth and postpartum support in the Seattle area.",
    packagePrice: 1000,
    addonRate: 35,
    slidingScale: true,
    paymentPlans: true,
  },
  {
    id: "d-003",
    name: "Alex Rivera",
    photoUrl: "/assets/doulas/alex-rivera-upload.png",
    city: "Bellevue",
    state: "WA",
    pronouns: "she/her",
    zipCode: "98004",
    specialties: ["postpartum", "birth"],
    tags: ["Postpartum Doula", "Trauma-informed", "Birth Doula", "LGBTQ+ clients", "First time parents"],
    rating: 4.7,
    reviewCount: 10,
    testimonialCount: 10,
    bio: "Holistic doula committed to empowering families during pregnancy, birth, and the postpartum period.",
    packagePrice: 800,
    addonRate: 35,
    slidingScale: false,
    paymentPlans: true,
  },
  {
    id: "d-004",
    name: "Sam Taylor",
    photoUrl: "/assets/doulas/sam-taylor-portrait.svg",
    city: "Redmond",
    state: "WA",
    pronouns: "she/they",
    zipCode: "98052",
    specialties: ["birth"],
    tags: ["Birth Doula", "First time parents", "Trauma-informed"],
    rating: 4.9,
    reviewCount: 8,
    testimonialCount: 8,
    bio: "New to Aunti but experienced in supporting families through their birth journey.",
    packagePrice: 500,
    addonRate: 35,
    slidingScale: false,
    paymentPlans: false,
    isNew: true,
  },
  {
    id: "d-005",
    name: "Priya Nair",
    photoUrl: "/assets/doulas/priya-nair-portrait.svg",
    city: "Kirkland",
    state: "WA",
    pronouns: "she/her",
    zipCode: "98033",
    specialties: ["postpartum", "birth"],
    tags: ["Postpartum Doula", "Birth Doula", "Newborn care", "Overnight support", "First time parents"],
    rating: 4.8,
    reviewCount: 16,
    testimonialCount: 16,
    bio: "Postpartum specialist focused on newborn care education and overnight support for new parents.",
    packagePrice: 750,
    addonRate: 28,
    slidingScale: true,
    paymentPlans: true,
  },
  {
    id: "d-006",
    name: "Hannah Brooks",
    photoUrl: "/assets/doulas/hannah-brooks-portrait.svg",
    city: "Tacoma",
    state: "WA",
    pronouns: "she/her",
    zipCode: "98402",
    specialties: ["birth"],
    tags: ["Birth Doula", "Unmedicated birth", "Hospital birth", "Evidence-based", "First time parents"],
    rating: 4.7,
    reviewCount: 29,
    testimonialCount: 29,
    bio: "Calm, evidence-based labor support specializing in unmedicated and hospital births alike.",
    packagePrice: 950,
    addonRate: 32,
    slidingScale: false,
    paymentPlans: true,
  },
  {
    id: "d-007",
    name: "Aaliyah Thompson",
    photoUrl: "/assets/doulas/aaliyah-upload.png",
    city: "Renton",
    state: "WA",
    pronouns: "she/her",
    zipCode: "98055",
    specialties: ["birth", "full-spectrum"],
    tags: ["Birth Doula", "Full Spectrum Doula", "Trauma-informed", "Midwifery background", "BIPOC families"],
    rating: 4.9,
    reviewCount: 12,
    testimonialCount: 12,
    bio: "Trauma-informed full-spectrum doula with a background in midwifery assistance.",
    packagePrice: 1100,
    addonRate: 40,
    slidingScale: true,
    paymentPlans: true,
  },
  {
    id: "d-008",
    name: "Sofia Mendes",
    photoUrl: "/assets/doulas/sofia-mendes-portrait.svg",
    city: "Lynnwood",
    state: "WA",
    pronouns: "she/her",
    zipCode: "98036",
    specialties: ["postpartum", "full-spectrum"],
    tags: ["Postpartum Doula", "Full Spectrum Doula", "Lactation support", "Meal planning", "LGBTQ+ clients"],
    rating: 4.6,
    reviewCount: 9,
    testimonialCount: 9,
    bio: "Supports families through the fourth trimester with lactation guidance and meal planning.",
    packagePrice: 850,
    addonRate: 30,
    slidingScale: true,
    paymentPlans: false,
  },
  {
    id: "d-009",
    name: "Keiko Yamamoto",
    photoUrl: "/assets/doulas/keiko-upload.png",
    city: "Seattle",
    state: "WA",
    pronouns: "she/her",
    zipCode: "98115",
    specialties: ["full-spectrum", "postpartum"],
    tags: ["Full Spectrum Doula", "Postpartum Doula", "Bilingual (Japanese)", "LGBTQ+ clients", "Cultural sensitivity"],
    rating: 5.0,
    reviewCount: 7,
    testimonialCount: 7,
    bio: "Bilingual Japanese-English full-spectrum doula offering culturally sensitive care for diverse families.",
    packagePrice: 1200,
    addonRate: 45,
    slidingScale: false,
    paymentPlans: true,
    isNew: true,
  },
  {
    id: "d-010",
    name: "Carmen Rodriguez",
    photoUrl: "/assets/doulas/carmen-rodriguez-portrait.svg",
    city: "Burien",
    state: "WA",
    pronouns: "she/her",
    zipCode: "98146",
    specialties: ["birth", "postpartum"],
    tags: ["Birth Doula", "Postpartum Doula", "Bilingual (Spanish)", "BIPOC families", "Sliding scale"],
    rating: 4.8,
    reviewCount: 19,
    testimonialCount: 19,
    bio: "Spanish-English bilingual doula dedicated to making compassionate birth support accessible to all families.",
    packagePrice: 700,
    addonRate: 25,
    slidingScale: true,
    paymentPlans: true,
  },
  {
    id: "d-011",
    name: "Maria Gonzalez",
    photoUrl: "/assets/doulas/maria-gonzalez-portrait.svg",
    city: "Austin",
    state: "TX",
    pronouns: "she/her",
    zipCode: "78701",
    specialties: ["birth", "postpartum"],
    tags: ["Birth Doula", "Postpartum Doula", "Bilingual (Spanish)", "7 years experience", "Central Texas"],
    rating: 4.9,
    reviewCount: 38,
    testimonialCount: 38,
    bio: "Bilingual birth and postpartum doula with 7 years supporting families across central Texas.",
    packagePrice: 900,
    addonRate: 30,
    slidingScale: true,
    paymentPlans: true,
  },
  {
    id: "d-012",
    name: "Jasmine Carter",
    photoUrl: "/assets/doulas/jasmine-carter-portrait.svg",
    city: "Austin",
    state: "TX",
    pronouns: "she/her",
    zipCode: "78704",
    specialties: ["full-spectrum"],
    tags: ["Full Spectrum Doula", "Trauma-informed", "Pregnancy decisions", "Postpartum recovery"],
    rating: 5.0,
    reviewCount: 21,
    testimonialCount: 21,
    bio: "Full-spectrum doula offering support from early pregnancy decisions through postpartum recovery.",
    packagePrice: 1100,
    addonRate: 40,
    slidingScale: false,
    paymentPlans: false,
  },
];